[build]
  publish = "/"

[build.environment]
  NODE_VERSION = "16"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirect rule for Netlify admin, if needed
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200 