[build]
  publish = "/"

[build.environment]
  NODE_VERSION = "16"

# Skip build commands since we're serving static HTML
# No build command means Netlify will just publish the files

# Redirect rule for static site
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]} 