backend:
  name: git-gateway
  branch: main # Or your main branch name

media_folder: "images/blog" # Media files will be stored here
public_folder: "/images/blog" # The src attribute for uploaded media

# Improve the Markdown editor experience
editor:
  preview: true # Show preview panel

# Add custom preview styles
locale: 'en'
site_url: https://centrallandscapingandpaving.ie

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    extension: "html" # Explicitly set HTML extension
    format: "frontmatter"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: true}
      - {label: "Description", name: "description", widget: "text", required: true}
      - {label: "Body", name: "body", widget: "markdown", required: true} 